import type { CategoryId } from "./constants";

export type SeedProduct = {
  name: string
  category: CategoryId
  volume: string
  price: number
  brand: string
  family: string
  description: string
  topNotes: string
  heartNotes: string
  baseNotes: string
  stock: number
  photoUrl: string
};

export const SEED_PRODUCTS: SeedProduct[] = [
  {
    name: "Bloom Rose",
    category: "women",
    volume: "10 мл",
    price: 7900,
    brand: "Aroma",
    family: "цветочные",
    description: "Свежая роза с мягкой пудрой. Лёгкий дневной аромат.",
    topNotes: "роза, роса",
    heartNotes: "пион, пудра",
    baseNotes: "мускус, сандал",
    stock: 14,
    photoUrl: "/products/bloom-rose.jpg",
  },
  {
    name: "Velvet Peony",
    category: "women",
    volume: "10 мл",
    price: 8500,
    brand: "Aroma",
    family: "цветочно-древесные",
    description: "Бархатный пион, который садится теплом и тихой древесиной.",
    topNotes: "пион, розовый перец",
    heartNotes: "роза, ирис",
    baseNotes: "мускус, кедр",
    stock: 11,
    photoUrl: "/products/velvet-peony.jpg",
  },
  {
    name: "White Musk",
    category: "women",
    volume: "5 мл",
    price: 4900,
    brand: "Aroma",
    family: "мускусные",
    description: "Чистый белый мускус. Мягкий шлейф на весь день.",
    topNotes: "хлопок, груша",
    heartNotes: "белый мускус, ирис",
    baseNotes: "сандал, амбра",
    stock: 18,
    photoUrl: "/products/white-musk.jpg",
  },
  {
    name: "Citrus Bloom",
    category: "women",
    volume: "10 мл",
    price: 6900,
    brand: "Aroma",
    family: "цитрусово-цветочные",
    description: "Бергамот и цветущий апельсин. Солнечный, лёгкий, на каждый день.",
    topNotes: "бергамот, апельсин",
    heartNotes: "нероли, зелень",
    baseNotes: "белый мускус, кедр",
    stock: 16,
    photoUrl: "/products/citrus-bloom.jpg",
  },
  {
    name: "Soft Vanilla",
    category: "women",
    volume: "10 мл",
    price: 7500,
    brand: "Aroma",
    family: "восточно-гурманские",
    description: "Тёплая ваниль без сладости. Уютный вечер, не десерт.",
    topNotes: "ваниль, бергамот",
    heartNotes: "тонковые бобы, молоко",
    baseNotes: "сандал, мускус",
    stock: 12,
    photoUrl: "/products/soft-vanilla.jpg",
  },
  {
    name: "Night Orchid",
    category: "women",
    volume: "5 мл",
    price: 5500,
    brand: "Aroma",
    family: "восточно-цветочные",
    description: "Тёмная орхидея и тихая амбра. Вечерний, собранный, чуть дымный.",
    topNotes: "орхидея, бергамот",
    heartNotes: "жасмин, специи",
    baseNotes: "амбра, дым",
    stock: 9,
    photoUrl: "/products/night-orchid.jpg",
  },
  {
    name: "Cedar Wood",
    category: "men",
    volume: "10 мл",
    price: 8900,
    brand: "Aroma",
    family: "древесные",
    description: "Сухой кедр и тёплое дерево. Спокойный, собранный, без сладости.",
    topNotes: "кедр, кардамон",
    heartNotes: "ветивер, кипарис",
    baseNotes: "дерево, мох",
    stock: 13,
    photoUrl: "/products/cedar-wood.jpg",
  },
  {
    name: "Fresh Vetiver",
    category: "men",
    volume: "10 мл",
    price: 7900,
    brand: "Aroma",
    family: "фужерные",
    description: "Свежий ветивер с цитрусом. Прохладный, зелёный, на каждый день.",
    topNotes: "лимон, мята",
    heartNotes: "ветивер, зелень",
    baseNotes: "кедр, мускус",
    stock: 15,
    photoUrl: "/products/fresh-vetiver.jpg",
  },
  {
    name: "Amber Leather",
    category: "men",
    volume: "5 мл",
    price: 5900,
    brand: "Aroma",
    family: "кожаные",
    description: "Кожа и амбра с лёгким дымом. Вечерний профиль без резкости.",
    topNotes: "перец, бергамот",
    heartNotes: "кожа, ладан",
    baseNotes: "амбра, дерево",
    stock: 10,
    photoUrl: "/products/amber-leather.jpg",
  },
  {
    name: "Marine Citrus",
    category: "men",
    volume: "10 мл",
    price: 6500,
    brand: "Aroma",
    family: "водные",
    description: "Морской бриз и лимон. Светлый, сухой, как прогулка у воды.",
    topNotes: "лимон, морская соль",
    heartNotes: "водоросли, нероли",
    baseNotes: "кедр, амбра",
    stock: 17,
    photoUrl: "/products/marine-citrus.jpg",
  },
  {
    name: "Black Pepper",
    category: "men",
    volume: "10 мл",
    price: 8200,
    brand: "Aroma",
    family: "пряно-древесные",
    description: "Чёрный перец и тёплый кедр. Острый старт, спокойная база.",
    topNotes: "чёрный перец, кардамон",
    heartNotes: "имбирь, лаванда",
    baseNotes: "кедр, ветивер",
    stock: 11,
    photoUrl: "/products/black-pepper.jpg",
  },
  {
    name: "Tobacco Smoke",
    category: "men",
    volume: "5 мл",
    price: 6200,
    brand: "Aroma",
    family: "восточные",
    description: "Табак и ваниль с лёгким дымом. Тёплый, мягкий, без тяжести.",
    topNotes: "табак, апельсин",
    heartNotes: "ваниль, тонковые бобы",
    baseNotes: "дым, дерево",
    stock: 8,
    photoUrl: "/products/tobacco-smoke.jpg",
  },
  {
    name: "Tea & Bergamot",
    category: "unisex",
    volume: "10 мл",
    price: 7200,
    brand: "Aroma",
    family: "цитрусово-ароматические",
    description: "Зелёный чай и бергамот. Чистый, лёгкий, как утро на террасе.",
    topNotes: "бергамот, зелёный чай",
    heartNotes: "жасмин, лист",
    baseNotes: "мускус, кедр",
    stock: 14,
    photoUrl: "/products/tea-bergamot.jpg",
  },
  {
    name: "Fig Garden",
    category: "unisex",
    volume: "10 мл",
    price: 8100,
    brand: "Aroma",
    family: "древесно-фруктовые",
    description: "Тёплый унисекс с инжиром и зелёным листом.",
    topNotes: "инжир, бергамот",
    heartNotes: "зелень, молоко",
    baseNotes: "дерево, мускус",
    stock: 12,
    photoUrl: "/products/fig-garden.jpg",
  },
  {
    name: "Warm Sandal",
    category: "unisex",
    volume: "5 мл",
    price: 5200,
    brand: "Aroma",
    family: "древесные",
    description: "Кремовый сандал и мягкий мускус. Тёплый, спокойный, близко к коже.",
    topNotes: "сандал, кардамон",
    heartNotes: "молоко, ирис",
    baseNotes: "мускус, дерево",
    stock: 16,
    photoUrl: "/products/warm-sandal.jpg",
  },
  {
    name: "Pink Pepper",
    category: "unisex",
    volume: "10 мл",
    price: 7400,
    brand: "Aroma",
    family: "пряно-цветочные",
    description: "Розовый перец и сухая роза. Лёгкая острота, чистый шлейф.",
    topNotes: "розовый перец, бергамот",
    heartNotes: "роза, герань",
    baseNotes: "кедр, мускус",
    stock: 13,
    photoUrl: "/products/pink-pepper.jpg",
  },
  {
    name: "Clean Cotton",
    category: "unisex",
    volume: "10 мл",
    price: 6300,
    brand: "Aroma",
    family: "мускусные",
    description: "Свежий хлопок и воздух. Чистый, тихий, почти незаметный на старте.",
    topNotes: "воздух, лимон",
    heartNotes: "хлопок, ирис",
    baseNotes: "белый мускус, кедр",
    stock: 18,
    photoUrl: "/products/clean-cotton.jpg",
  },
  {
    name: "Oud Soft",
    category: "unisex",
    volume: "5 мл",
    price: 6800,
    brand: "Aroma",
    family: "восточно-древесные",
    description: "Мягкий уд без резкости. Тёплый глубокий шлейф, не тяжёлый.",
    topNotes: "шафран, бергамот",
    heartNotes: "уд, роза",
    baseNotes: "сандал, амбра",
    stock: 9,
    photoUrl: "/products/oud-soft.jpg",
  },
];
