/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as ApiTelegramRouteImport } from './routes/api/telegram'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as SuccessOrderIdRouteImport } from './routes/success.$orderId'
import { Route as AdminProductsIndexRouteImport } from './routes/admin.products.index'
import { Route as AdminProductsIdRouteImport } from './routes/admin.products.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const ApiTelegramRoute = ApiTelegramRouteImport.update({
  id: '/api/telegram',
  path: '/api/telegram',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessOrderIdRoute = SuccessOrderIdRouteImport.update({
  id: '/success/$orderId',
  path: '/success/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminProductsRoute,
} as any)
const AdminProductsIdRoute = AdminProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminProductsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/orders': typeof OrdersRoute
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/api/telegram': typeof ApiTelegramRoute
  '/product/$id': typeof ProductIdRoute
  '/success/$orderId': typeof SuccessOrderIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/admin/products/': typeof AdminProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/orders': typeof OrdersRoute
  '/api/telegram': typeof ApiTelegramRoute
  '/product/$id': typeof ProductIdRoute
  '/success/$orderId': typeof SuccessOrderIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/admin/products': typeof AdminProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/orders': typeof OrdersRoute
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/api/telegram': typeof ApiTelegramRoute
  '/product/$id': typeof ProductIdRoute
  '/success/$orderId': typeof SuccessOrderIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/admin/products/': typeof AdminProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/orders'
    | '/admin/products'
    | '/api/telegram'
    | '/product/$id'
    | '/success/$orderId'
    | '/admin/'
    | '/admin/products/$id'
    | '/admin/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/orders'
    | '/api/telegram'
    | '/product/$id'
    | '/success/$orderId'
    | '/admin'
    | '/admin/products/$id'
    | '/admin/products'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/orders'
    | '/admin/products'
    | '/api/telegram'
    | '/product/$id'
    | '/success/$orderId'
    | '/admin/'
    | '/admin/products/$id'
    | '/admin/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  OrdersRoute: typeof OrdersRoute
  ApiTelegramRoute: typeof ApiTelegramRoute
  ProductIdRoute: typeof ProductIdRoute
  SuccessOrderIdRoute: typeof SuccessOrderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/telegram': {
      id: '/api/telegram'
      path: '/api/telegram'
      fullPath: '/api/telegram'
      preLoaderRoute: typeof ApiTelegramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success/$orderId': {
      id: '/success/$orderId'
      path: '/success/$orderId'
      fullPath: '/success/$orderId'
      preLoaderRoute: typeof SuccessOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof AdminProductsRoute
    }
    '/admin/products/$id': {
      id: '/admin/products/$id'
      path: '/$id'
      fullPath: '/admin/products/$id'
      preLoaderRoute: typeof AdminProductsIdRouteImport
      parentRoute: typeof AdminProductsRoute
    }
  }
}

interface AdminProductsRouteChildren {
  AdminProductsIdRoute: typeof AdminProductsIdRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
}

const AdminProductsRouteChildren: AdminProductsRouteChildren = {
  AdminProductsIdRoute: AdminProductsIdRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
}

const AdminProductsRouteWithChildren = AdminProductsRoute._addFileChildren(
  AdminProductsRouteChildren,
)

interface AdminRouteChildren {
  AdminProductsRoute: typeof AdminProductsRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminProductsRoute: AdminProductsRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  OrdersRoute: OrdersRoute,
  ApiTelegramRoute: ApiTelegramRoute,
  ProductIdRoute: ProductIdRoute,
  SuccessOrderIdRoute: SuccessOrderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
